{
	"notifications" : [
			{
				"date" : "2012-08-22T11:09:29-0400",
				"header" : "Simple Notification",
				"systemId" : "261",
				"siteId" : "18",
				"siteName" : "Illinois Primary Healthcare",
				"notificationId" : "21633",
				"studyId" : null,
				"studyName" : "ZZ_MCRA Pro 1",
				"notificationText" : "First Patient has Enrolled at Site, No Reset",
				"read" : true,
				"important" : true,
				"alertId" : "2",
				"alertResetRequired" : false
			},
			{
				"date" : "2012-08-22T11:09:18-0400",
				"header" : "Simple Notification",
				"systemId" : "261",
				"siteId" : "7",
				"siteName" : "Amsterdam Cardiology Department",
				"notificationId" : "21632",
				"studyId" : null,
				"studyName" : "AMXN 9374",
				"notificationText" : "No of enrolled Patient is higher then <number of enrolled patient>",
				"read" : true,
				"important" : false,
				"alertId" : "7",
				"alertResetRequired" : false
			},
			{
				"date" : "2012-08-22T11:04:59-0400",
				"header" : "Simple Notification",
				"systemId" : "261",
				"siteId" : "18",
				"siteName" : "Illinois Primary Healthcare",
				"notificationId" : "21629",
				"studyId" : null,
				"studyName" : "ZZ_MCRA Pro 1",
				"notificationText" : "First Patient has Enrolled at Site, No Reset",
				"read" : true,
				"important" : false,
				"alertId" : "2",
				"alertResetRequired" : false
			},
			{
				"date" : "2012-08-22T11:04:48-0400",
				"header" : "Simple Notification",
				"systemId" : "261",
				"siteId" : "7",
				"siteName" : "Amsterdam Cardiology Department",
				"notificationId" : "21628",
				"studyId" : null,
				"studyName" : "AMXN 9374",
				"notificationText" : "No of enrolled Patient is higher then <number of enrolled patient>",
				"read" : true,
				"important" : true,
				"alertId" : "7",
				"alertResetRequired" : false
			},
			{
				"date" : "2012-08-22T10:59:44-0400",
				"header" : "Simple Notification",
				"systemId" : "261",
				"siteId" : "18",
				"siteName" : "Illinois Primary Healthcare",
				"notificationId" : "21625",
				"studyId" : null,
				"studyName" : "ZZ_MCRA Pro 1",
				"notificationText" : "First Patient has Enrolled at Site, No Reset",
				"read" : true,
				"important" : false,
				"alertId" : "2",
				"alertResetRequired" : false
			},
			{
				"date" : "2012-08-22T10:59:33-0400",
				"header" : "Simple Notification",
				"systemId" : "261",
				"siteId" : "7",
				"siteName" : "Amsterdam Cardiology Department",
				"notificationId" : "21624",
				"studyId" : null,
				"studyName" : "AMXN 9374",
				"notificationText" : "No of enrolled Patient is higher then <number of enrolled patient>",
				"read" : true,
				"important" : false,
				"alertId" : "7",
				"alertResetRequired" : false
			},
			{
				"date" : "2012-08-22T10:54:42-0400",
				"header" : "Simple Notification",
				"systemId" : "261",
				"siteId" : "18",
				"siteName" : "Illinois Primary Healthcare",
				"notificationId" : "21621",
				"studyId" : null,
				"studyName" : "ZZ_MCRA Pro 1",
				"notificationText" : "First Patient has Enrolled at Site, No Reset",
				"read" : true,
				"important" : false,
				"alertId" : "2",
				"alertResetRequired" : false
			},
			{
				"date" : "2012-08-22T10:54:31-0400",
				"header" : "Simple Notification",
				"systemId" : "261",
				"siteId" : "7",
				"siteName" : "Amsterdam Cardiology Department",
				"notificationId" : "21620",
				"studyId" : null,
				"studyName" : "AMXN 9374",
				"notificationText" : "No of enrolled Patient is higher then <number of enrolled patient>",
				"read" : true,
				"important" : false,
				"alertId" : "7",
				"alertResetRequired" : false
			},
			{
				"date" : "2012-08-22T10:49:43-0400",
				"header" : "Simple Notification",
				"systemId" : "261",
				"siteId" : "18",
				"siteName" : "Illinois Primary Healthcare",
				"notificationId" : "21617",
				"studyId" : null,
				"studyName" : "ZZ_MCRA Pro 1",
				"notificationText" : "First Patient has Enrolled at Site, No Reset",
				"read" : true,
				"important" : false,
				"alertId" : "2",
				"alertResetRequired" : false
			},
			{
				"date" : "2012-08-22T10:49:31-0400",
				"header" : "Simple Notification",
				"systemId" : "261",
				"siteId" : "7",
				"siteName" : "Amsterdam Cardiology Department",
				"notificationId" : "21616",
				"studyId" : null,
				"studyName" : "AMXN 9374",
				"notificationText" : "No of enrolled Patient is higher then <number of enrolled patient>",
				"read" : true,
				"important" : false,
				"alertId" : "7",
				"alertResetRequired" : false
			},
			{
				"date" : "2012-08-22T10:44:58-0400",
				"header" : "Simple Notification",
				"systemId" : "261",
				"siteId" : "18",
				"siteName" : "Illinois Primary Healthcare",
				"notificationId" : "21613",
				"studyId" : null,
				"studyName" : "ZZ_MCRA Pro 1",
				"notificationText" : "First Patient has Enrolled at Site, No Reset",
				"read" : false,
				"important" : false,
				"alertId" : "2",
				"alertResetRequired" : false
			},
			{
				"date" : "2012-08-22T10:44:47-0400",
				"header" : "Simple Notification",
				"systemId" : "261",
				"siteId" : "7",
				"siteName" : "Amsterdam Cardiology Department",
				"notificationId" : "21612",
				"studyId" : null,
				"studyName" : "AMXN 9374",
				"notificationText" : "No of enrolled Patient is higher then <number of enrolled patient>",
				"read" : true,
				"important" : false,
				"alertId" : "7",
				"alertResetRequired" : false
			} ],
	"nextPageStartId" : "21609"
}